---
title: ""
output:
  html_document:
    theme: spacelab
    highlight: textmate 
---
<br>

#### Laboratory: sensorimotor function and its age- and disease-related deficits

In the group of Prof. Orban de Xivry, we aim at understanding the mechanisms of motor control and learning and which of these mechanisms is affected by aging or by disease (Parkinson’s disease, stroke or cancer).  This is achieved mostly by studying the movement kinematics in simplified and well-controlled paradigms. Yet, while such paradigms have been valuable for our understanding of age- and disease-related changes in motor function, it limits our ability to explore the complexities of neural processing. Therefore, we are developing a research program that brings the real-world complexities into action such as during biking. Behavioral approaches are complemented by neuroimaging or brain stimulation studies when these bring added value to our understanding. For instance, we are currently investigating the role of the cerebellum in age-related deficits in motor control by means of structural and functional neuroimaging. We are a team of multidisciplinary scientists with diverse backgrounds: rehabilitation sciences, movement sciences, neuroscience, psychology or a more computational background (engineering).
<br>

#### Prof. Jean-Jacques Orban de Xivry

[Department of Movement Sciences](https://gbiomed.kuleuven.be/english/research/50000737)<br>
[Leuven Brain Institute](https://gbiomed.kuleuven.be/english/LBI)<br>
KU Leuven, Belgium
<br>

#### Contact information

__Surname__: JJ
<br>
__Mastodon__: [@jjodx@neuromatch.social](https://neuromatch.social/@jjodx)  (__BlueSky__: [@jjodx.bsky.social](https://bsky.app/profile/jjodx.bsky.social))
<br>
__Email__: jj.orban AT kuleuven DOT be
<br>
__Address__:
Gebouw De Nayer, room 01.55<br>
Tervuursevest 101 - box 1501<br>
3001 Leuven<br>
Belgium<br>

#### who am I

<p> I am an engineer in applied mathematics who did his PhD (2002-2007) on computational neuroscience at the Université catholique de Louvain (Belgium). During my PhD, I focused on eye movements with applications to clinical populations. I went on to pursue my post-doctoral work (2008-2010) with Reza Shadmehr at Johns Hopkins University (Baltimore, MD, USA) where I used transcranial magnetic stimulation (TMS) and transcranial direct current stimulation (tDCS) to investigate the role of the motor cortex in motor adaptation. My post-doctoral stay at Hopkins was partially supported by a Fellowship from the Belgian American Educational Foundation. Then, I secured independent funding from the Brussels region (2011-2014: 610 000€) in order to pursue my research as an independent investigator at UCLouvain on how theories of motor control can be successfully applied to understand brain functions in health and disease.</p>

<p> Since December 2014, I am a Professor (2014-2019: assistant; now associated) at the department of Movement Sciences at KU Leuven where my project focuses on the effect of aging and neurological disease on motor control and learning via a multimodal approach (behavior, brain stimulation, EEG and structural MRI).</p> 

<p> In addition, I am one of the founding member of the BRain Activity, Imaging & NeuroStimulation for HUman Behaviour research platform (BRAINS-HUB, KU Leuven, Belgium) for which we received a small equipment grant from KU Leuven and, as co-PI, a large Hercules grant. </p>

<p> Finally, I decided to use state-of-the-art research methodologies for the research in my laboratory. All papers are first published as preprints (e.g. https://www.biorxiv.org/content/10.1101/292250v2). All data and code are made available on the Open Science Framework (e.g. https://osf.io/vncce/) and studies are pre-registered when possible (https://osf.io/n8bwf/). In addition, I try to provide several lines of evidence to backup the claims in my papers by replicating my own results and using larger group of participants (N=20 or 30 per group). One of our latest paper (Vandevoorde and Orban de Xivry 2019) is a good example of what we wants to achieve in the laboratory. </p>


#### Academic career

<p> __2019 - current__: Associate Professor in the Movement Control and Neuroplasticity Group, Faculty of Movement and Rehabilitation Sciences, KU Leuven, Belgium.</p>

<p> __2014 - 2019__: Assistant Professor in the Movement Control and Neuroplasticity Group, Faculty of Movement and Rehabilitation Sciences, KU Leuven, Belgium.</p>
<p> __2011-2014__: Post-Doc at Université catholique de Louvain with Philippe Lefèvre sponsored by the Brussels region (Grant Brains Back to Brussels).</p>
<p> __2007-2010__: Post-Doc in the [Laboratory of Computational Motor Control (Johns Hopkins University, USA)](www.shadmehrlab.org) under the supervision of Prof. Reza Shadmehr.</p>
<p> __2002-2007__: PhD student at CESAME and Laboratory of Neurophysiology (UCL, Belgium). Thesis: Tracking the invisible requires prediction and internal models. Promotor: P. Lefèvre.</p>
<p> __1997-2002__: Study of engineer in applied mathematics. Master thesis: "Modeling of anticipatory responses build-up in repetitive oculomotor tasks" with P. Lefèvre and G. Blohm</p>

#### Academic services
- reviewing Editor at eLife (2023-current)
- Active reviewer for many different journals in the field of movement neuroscience.
- Elected board member of the [Neural Control of Movement society](www.ncm-society.org) Term: 2014-2017; Renewed:2018-2020<br>
- Editorial board member of The Journal of Neuropshysiology<br>
- Member of the taskforce on TMS for the Belgian Health Council (2013) <br>
- Grant reviewer for ANR (Agence National de la Recherche, France); CNC (National Science Centre, Poland) ; ISF (Israel Science Foundation), AXA fellowships, NSERC (Canada), UC Davis (USA)<br>

#### KU Leuven services

- Founding member of the Young ZAP club of the biomedical sector at KU Leuven (2015-2020)
- Member of the think-tank on Open Science at KU Leuven (2019)
- Member of the review commission on teaching portfolio, sector of biomedical sciences (2019-current)
- Member of resonantieraad Metaforum (2019-current)
- Member of the sustainability council of KU Leuven (2020-2022)
- Member of the think-tank of societal impact of academic research of KU Leuven (2020-2022)
- Member of the departmental board of Movement Sciences (2020-current) 

#### Grants and Awards
<!--<p> __2024-2027__: [FWO](www.fwo.be) senior research project: Multifaceted approach to investigate position sense in health and disease (co-PI: An De Groef) </p>-->
<p> __2023-2026__: C2 project (internal grant from the KU Leuven): **MAeSTRo**: neuro-**M**usculoskeletal **AS**sessement and **TR**aining for safe (e-)cycling (co-PI: Friedl De Groote)</p>
<p> __2023-2026__: collaborator on a C2 project (internal grant from the KU Leuven) awarded to Geert Verheyden: **Robust**: integrated **ROB**otic **U**pper limb sensorimotor rehabilitation after **ST**roke to improve behavioural, objective and real-life outcome</p>
<p> __2022-2024__: Collaborator on a New Frontiers in Research Fund - Exploration grant entitled: "A unifying principle of cerebellar function" led by [Mireille Broucke](http://www.control.utoronto.ca/~broucke) and [Denise Henriques](https://deniseh.lab.yorku.ca/) </p>
<p> __2021-2024__: [FWO](www.fwo.be) senior research project: Is there a motor reserve in the cerebellum? </p>
<p> __2018-2020__: collaborator on a C2 internal Grant from KU Leuven with Geert Verheyden: Towards understanding upper limb rehabilitation after stroke</p>
<p> __2017-2021__: Internal Grant from KU Leuven with Alice Nieuwboer: Mechanisms of non-invasive brain stimulation to enhance consolidation of motor learning in Parkinson’s disease</p>
<p> __2019__: Hercules Grant (large equipment) from the [FWO](www.fwo.be): Integrated Platform for Closed-Loop Motor Training and Adaptive Neuromodulation (CLAN, co-PI, 878000€)</p>
<p> __2018__: Small equipment grant from the KU Leuven: Translational upper limb platform (TULiP) (main PI, 87 000€)</p>
<p> __2016-2018__: Krediet aan Navorser from the [FWO](www.fwo.be)</p>
<p> __2015-2019__: Starting grant from the KU Leuven</p>
<p> __2014-2016__ Collaborative Grant with Daichi Nozaki (University of Tokyo, Japan) funded by FNRS (Belgium) and JPSP (Japan)</p>
<p> __2011__ Travel Award to NCM meeting</p>
<p> __2010-2016__: Grant Brains Back to Brussels from the Brussels region (2010-2013, renewed for 2014-2016).</p>
<p> __2009__: Award from "Fondation pour la vocation" Belgium</p>
<p> __2009__ Travel Award for the Computational principles of sensorimotor learning (Irsee, Germany)</p>
<p> __2007__: Grant from the [Belgian American Educational Foundation](www.baef.be) </p>
<p> __2007__: Grant "Fonds spéciaux de recherche" from the Université catholique de Louvain </p>
<p> __2007__:Grant "Bourse de séjour scientifique" from the "Fonds National pour la Recherche Scientifique", Belgium</p>
    



