---
title: "Laboratory of JJ Orban de Xivry"
output:
  html_document:
    theme: spacelab
    highlight: textmate
---
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">
<style>
p.ex1{
    padding-left: 20%;
}
#more {display: none;}
</style>

<div class = "col-md-2">


<a href="http://scholar.google.com/citations?user=Xfy7g78AAAAJ&hl=en">
<i style="color:  #4c9fec;" class="ai ai-google-scholar ai-3x" ></i>
</br>Scholar
</a>
<br>

<a href="http://www.twitter.com/jjodx">
<i style="color:  #4c9fec;" class="fa fa-twitter fa-3x" ></i>
</br>Twitter
</a>
<br>

<a href="https://orcid.org/0000-0002-4603-7939">
<i style="color: #4c9fec;" class="ai ai-orcid ai-3x" ></i>
</br>ORCID
</a>
<br>

<a href="https://www.researchgate.net/profile/Jj_Orban">
<i style="color: #4c9fec;" class="ai ai-researchgate ai-3x" ></i>
</br>ResearchGate
</a>
<br>

<a href="https://osf.io/2pgq5/">
<i style="color: #4c9fec;" class="ai ai-osf ai-3x" ></i>
</br>OSF
</a>
<br>

<a href="https://github.com/jjodx">
<i style="color: #4c9fec;" class="fa fa-github fa-3x" ></i>
</br>GitHub
</a>
<br>

</div>

<div class = "col-md-7">
<style>
div.intro { background-color:#e6e6e6; border-radius: 25px; padding: 20px;}
</style>
<div class = "intro">
#### our mission:

We aim at understanding how the brain controls our movements and how it learns to perform new ones by means of detailed kinematic analyses of movement trajectories. We focus on age- and disease-related effects on these sensorimotor processes.
</div>
<br>

## latest news

<p class="ex1">
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}


</style>
<p>
<div class = "blue">
<font size="2"> **December 2022** </font><br>
Congratulations to Leen Saenen for defending her PhD entitled: *Upper limb sensory processing: development of a robotic paradigm*.
</div>
<br>

<div class = "blue">
<font size="2"> **Nov 2022** </font><br>
Congratulations to Silke Kerstens for a new paper: [A novel tDCS control condition using optimized anesthetic gel to block peripheral nerve input](https://www.frontiersin.org/articles/10.3389/fneur.2022.1049409/full). First of a series with [Myles McLaughlin](https://gbiomed.kuleuven.be/english/research/50000666/50000672/people/members/00043883) </div>
<br>

<div class = "blue">
<font size="2"> **Nov 2022** </font><br>
Take-over of Twitter by EM did not please many people including me... Therefore, I am tweeting less and tooting more. You can find me at [@jjodx@fediscience.org](https://fediscience.org/@jjodx) </div>
<br>

<div class = "blue">
<font size="2"> **July 2022** </font><br>
Congratulations to Leen Saenen for her first first-author paper on sensory processing/haptic perception in stroke patients: [Development and Validation of a Novel Robot-Based Assessment of Upper Limb Sensory Processing in Chronic Stroke](https://www.mdpi.com/2076-3425/12/8/1005). First joint paper with my colleague [Geert Verheyden](https://www.kuleuven.be/wieiswie/en/person/00029759)<br>
Leen also has a new preprint on the effect of age on haptic perception : [The differential effect of age on upper limb sensory processing, proprioception and motor function](https://www.biorxiv.org/content/10.1101/2022.08.26.505430v1)</div>
<br>

<div class = "blue">
<font size="2"> **summer 2022** </font><br>
JJ goes to Canada for his sabbatical until summer 2023. He will work with Andrew Pruszynski, Joern Diedrichsen and Paul Gribble at Western University (London,ON, Canada)
</div>
<br>

<div class = "blue">
<font size="2"> **May-June 2022** </font><br>
Bike project will not be funded by an internal grant of KU Leuven, at least not this year. But comments are encouraging and give us food for thoughts. It's rejection season, no fellowship from FWO to Anouck either (not yet ;-) )
</div>
<br>

<div class = "blue">
<font size="2"> **1st of May 2022** </font><br>
 We are sad to see Matheus Maia Pacheco leaving our group but we wish a lot of success for his new adventure as an assistant Professor at the University of Porto in Portugal.
</div>
<br>

<div class = "blue">
<font size="2"> **March-April 2022** </font><br>
Many grants and fellowship were submitted:

-   application for a FWO PhD fellowship for Anouck Mathijs
-   senior FWO research project with An De Groef
-   C2 internal grant on the bike project with Friedl De Groote, Jannique Van Uffelen and Kathrin Gerling.
</div>
<br>

<div class = "blue">
<font size="2"> **March 2022** </font><br>
The first pre-print of our bike project with Maarten Afschrift, Anouck Mathijs and Friedl De Groote is out: [Turning the head while biking makes older people lose cycling direction and balance](https://doi.org/10.1101/2022.03.01.481993)
</div>
<br>
<!--  source collapsible elements: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab -->

<details>
  <summary>Older News</summary>

<div class = "blue">
<font size="2"> **November 2021** </font><br>
Just before Christmas, the first paper of Manasa Parthasharathy has been accepted for publication at the Journal of Neuropshysiology: [Increased upper-limb sensory attenuation with age](https://journals.physiology.org/doi/abs/10.1152/jn.00558.2020)
</div>
<br>

<div class = "blue">
<font size="2"> **November 2021** </font><br>
We waved goodbye to Manasa Parthasharathy who became Business Development Manager at icometrix 
</div>
<br>

<div class = "blue">
<font size="2"> **Summer 2021** </font><br>
Our team is growing. We welcome Anda De Witte on the 1st of July and Anouck Matthijs on the 1st of September. They will work on the FWO-funded project: "Is there a motor reserve in the cerebellum". Exciting times!
</div>
<br>

<div class = "blue">
<font size="2"> **23 July 2021** </font><br>
The last paper from the PhD of Koen Vandevoorde has been accepted for publication in the Journal of Neurophysiology:  "[Does proprioceptive acuity influence the extent of implicit sensorimotor adaptation in young and older adults?](https://journals.physiology.org/doi/abs/10.1152/jn.00636.2020)". This is the last piece of a very enjoyable and fruitful collaboration.
</div>
<br>

<div class = "blue">
<font size="2"> **31 May 2021** </font><br>
Congrats to Veerle for the acceptance of her first first-author paper entitled "[Compromised Brain Activity With Age During a Game-Like Dynamic Balance Task: Single- vs. Dual-Task Performance](https://www.frontiersin.org/articles/10.3389/fnagi.2021.657308/full)". Well done Veerle !
</div>
<br>

<div class = "blue">
<font size="2"> **22nd of March, 2021** </font><br>
Last paper from the PhD thesis of Guy Rens has been accepted at Neuropsychologia: Motor resonance is modulated by an object’s weight distribution. Well done Guy! <i style='color: #211f1f;' class='ai ai-biorxiv ai-1x' ></i> [Preprint](https://www.biorxiv.org/content/10.1101/2020.10.11.335000v3)
</div>
<br>

<div class = "blue">
<font size="2"> **15th of March, 2021** </font><br>
<i style='color: #211f1f;' class='ai ai-biorxiv ai-1x' ></i>
New preprint with Ryan Morehead (Leeds University, UK): [A Synthesis of the Many Errors and Learning Processes of Visuomotor Adaptation](https://www.biorxiv.org/content/10.1101/2021.03.14.435278v1).<br>
The tweeprint <i style="color:  #4c9fec;" class="fa fa-twitter fa-1x" ></i> made by Ryan is available here: [https://twitter.com/rmhead/status/1371669385367195648](https://twitter.com/rmhead/status/1371669385367195648) 
</div>
<br>

<div class = "blue">
<font size="2"> **February/March, 2021** </font><br>
I am recruiting two PhD students to work on a FWO-funded project focused on cerebellar motor functions, aging and structural imaging. Please apply here: [https://www.kuleuven.be/personeel/jobsite/jobs/56170382](https://www.kuleuven.be/personeel/jobsite/jobs/56170382)
</div>
<br>

<div class = "blue">
<font size="2"> **February/March, 2021** </font><br>
Dante Mantini and Jean-Jacques are thrilled to welcome Matheus Pacheco <a href="https://twitter.com/Piolho_eefe">
<i style="color:  #4c9fec;" class="fa fa-twitter fa-1x" ></i>
</a> as a post-doc. Matheus will use EEG to unravel age-related changes in error processing.
</div>
<br>

<div class = "blue">
<font size="2"> **January 2021** </font><br>
JJ was interviewed on Open Science. You can read the interview here:  [*An open scientist helps research and himself or herself to move forward*](https://www.kuleuven.be/open-science/news/2021/J-J_Orban) 
</div>
<br>

<div class = "blue">
<font size="2"> **January 20th 2021** </font><br>
Congrats to Guy Rens who got his paper entitled "*Lift observation conveys object weight distribution but partly enhances predictive lift planning*" accepted for publication in the Journal of Neurophysiology.<br> <i style='color: #211f1f;' class='ai ai-biorxiv ai-2x' ></i> [Preprint](https://www.biorxiv.org/content/10.1101/2020.06.21.163352v4)
</div>
<br>

<div class = "blue">
<font size="2"> **December, 2020** </font><br>
Jean-Jacques got a grant from the [FWO (Flemish Research Foundation)](https://www.fwo.be/) to work on a project entitled: "Is there a motor reserve in the cerebellum". This project focuses on measuring age-related changes in motor function based on a large task battery and included structural MRI as well.
</div>
<br>

<div class = "blue">
<font size="2"> **November, 2020** </font><br>
Paper with Friedl De Groote <a href="https://twitter.com/friedldegroote">
<i style="color:  #4c9fec;" class="fa fa-twitter fa-1x" ></i>
</a>, Stefanie Vandevyvere and Florian Vanhevel accepted by Gait & Posture (after a very long review process that did not really change the paper) ([paper](https://pubmed.ncbi.nlm.nih.gov/33260077/)). Preprint is available [here](https://www.biorxiv.org/content/10.1101/2020.05.29.123620v1). Data <i style='color: #0f6cd6;' class='ai ai-open-data ai-1x' ></i> and code <i style='color: #211f1f;' class='fa fa-github fa-1x' ></i> are on the Open Science Framework ([LINK](https://osf.io/vpd79/?view))
</div>
<br>

<div class = "blue">
<font size="2"> **October, 2020** </font><br>
We have several preprints <i style='color: #211f1f;' class='ai ai-biorxiv ai-2x' ></i> out there:<br>
Manasa Parthasharathy: [Increased upper-limb sensory attenuation with age](https://www.biorxiv.org/content/10.1101/2020.09.17.301739v1)<br>
Koen Vandevoorde: [Does somatosensory acuity influence the extent of internal model recalibration in young and older adults?](https://www.biorxiv.org/content/10.1101/2020.10.16.342295v1)<br>
Guy Rens: [Motor resonance is modulated by an object’s weight distribution](https://doi.org/10.1101/2020.10.11.335000)
</div>
<br>

<div class = "blue">
<font size="2"> **Octobre 1st, 2020** </font><br>
Stien Van De Plas starts her PhD today. Welcome Stien! She will work on the role of somatosensation on motor control for the next four years. Co-promotor is Dante Mantini.
</div>
<br>

<div class = "blue">
<font size="2"> **September 20, 2020** </font><br>
Two new papers published in the Special Issue of the Journal of Computational Neuroscience dedicated to Lance Optican. See the publication page.
</div>
<br>

<div class = "blue">
 <font size="2"> **July 1, 2020** </font><br>
Koen Vandevoorde's paper was published in Journal of Neurophysiology ([paper](https://doi.org/10.1152/jn.00659.2019)). Preprint is available [here](https://www.biorxiv.org/content/10.1101/753160v1)
</div>
<br>

<div class = "blue">
<font size="2"> **June 15, 2020** </font><br>
The departement of Movement Sciences is recruiting two tenure-track professors:

1. motor control and neuroimaging: [link](https://www.kuleuven.be/personeel/jobsite/jobs/55675790?hl=en&lang=en)

2. motor control and performance in competitive and elite sports: [link](https://www.kuleuven.be/personeel/jobsite/jobs/55676338)

Come and join us!!
</div>
<br>

<div class = "blue">
<font size="2"> **June 3, 2020** </font><br>
Together with Prof. Dante Mantini, we are recruiting a PhD student to work on the influence of a decline in somatosensory function on motor control and learning. Vacancy is available [here](https://www.kuleuven.be/personeel/jobsite/jobs/55671291?hl=en&lang=en)
Note, the candidate has to be fluent in Dutch as s/he has to act as teaching assistant in that language
</div>
<br>

<div class = "blue">
<font size="2"> **June 1st, 2020** </font><br>
Never forget to submit your paper as preprint first! We did forget to do it for this one but after being **4 months under review at Gait&Posture**, we decided that it was enough. Preprint entitled "Validation of a smartphone embedded inertial measurement unit for measuring postural stability in older adults" is available [here](https://www.biorxiv.org/content/10.1101/2020.05.29.123620v1)
</div>
<br>

<div class = "blue">
<font size="2"> **May 27, 2020** </font><br>
Together with Prof. Dante Mantini, we are recruiting a post-doc to work on EEG and motor adaptation. Vacancy is available [here](https://www.kuleuven.be/personeel/jobsite/jobs/55671214?hl=en&lang=en)
</div>
<br>

<div class = "blue">
 <font size="2"> __May 9, 2020__ </font><br>
Koen Vandevoorde got his paper accepted in Journal of Neurophysiology. Preprint is available [here](https://www.biorxiv.org/content/10.1101/753160v1)
</div>
<br>

<div class = "blue">
<font size="2"> __March 31, 2020__ </font><br>
Congrats to Guy Rens who got his paper entitled [Sensorimotor Expectations Bias Motor Resonance during Observation of Object Lifting: The Causal Role of pSTS]( https://doi.org/10.1523/JNEUROSCI.2672-19.2020) accepted in Journal of Neuroscience.
</div>
<br>

<div class = "blue">
<font size="2"> __Januari 20, 2020__ </font><br>
With Prof. Friedl De Groote, we submitted a paper entitled "_Validation of a smartphone embedded inertial measurement unit for measuring postural stability in older adults_" to Gait&Posture.
</div>
<br>

<div class = "blue">
 <font size="2"> __October, 2019__ </font><br>
Tamar Makin and JJ Orban de Xivry publish their paper on ten common statistical mistakes in eLife [here](https://elifesciences.org/articles/48175). Interview about the paper: [here](https://www.natureindex.com/news-blog/ten-most-common-mistakes-with-statistics-and-how-to-avoid-them)
</div>

</details>

<style>
.btn {
    border-width: 0 0px 0px 0px;
    font-weight: normal;
    text-transform: ;
}
.btn-default {
    color: #2ecc71;
    background-color: #ffffff;
    border-color: #ffffff;
}
</style>

</div>
</div>


<div class = "col-md-3">
<a href="http://twitter.com/jjodx" class="twitter-follow-button" data-show-count="false">Follow @jjodx</a>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>



<a class="twitter-timeline" data-lang="en" data-width="220" data-height="1000" data-dnt="true" data-theme="light" href="https://twitter.com/jjodx?ref_src=twsrc%5Etfw">Tweets by jjodx</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

</div>





