----
title: "My pubs"
----
# Preprint of papers
Vandevoorde and Orban de Xivry, Motor adaptation but not internal model recalibration declines with aging, BioRxiv, 2018

# Peer-reviewed publications

37 - Deravet, Blohm, Orban de Xivry and Lefèvre Weighted integration of short term memory and sensory signals in the oculomotor system, Journal of Vision, 2018 Preprint

36 - Daniel Lakens, Federico Adolfi, Casper Albers, Farid Anvari, Matthew Apps, Shlomo Argamon, Thom Baguley, Raymond Becker, Stephen Benning, Daniel Bradford, Erin Buchanan, Aaron Caldwell, Ben Van Calster, Rickard Carlsson, Sau-Chin Chen, Bryan Chung, Lincoln Colling, Gary Collins, Zander Crook, Emily Cross, Sameera Daniels, Henrik Danielsson, Lisa DeBruine, Daniel Dunleavy, Brian Earp, Michele Feist, Jason Ferrell, James Field, Nicholas Fox, Amanda Friesen, Caio Gomes, Monica Gonzalez-Marquez, James Grange, Andrew Grieve, Robert Guggenberger, James Grist, Anne-Laura van Harmelen, Fred Hasselman, Kevin Hochard, Mark Hoffarth, Nicholas Holmes, Michael Ingre, Peder Isager, Hanna Isotalus, Christer Johansson, Konrad Juszczyk, David Kenny, Ahmed Khalil, Barbara Konat, Junpeng Lao, Erik Larsen, Gerine Lodder, Jiří Lukavský, Christopher Madan, David Manheim, Stephen Martin, Andrea Martin, Deborah Mayo, Randy McCarthy, Kevin McConway, Colin McFarland, Amanda Nio, Gustav Nilsonne, Cilene Lino de Oliveira, Jean-Jacques Orban de Xivry, Sam Parsons, Gerit Pfuhl, Kimberly Quinn, John Sakon, Selahattin Saribay, Iris Schneider, Manojkumar Selvaraju, Zsuzsika Sjoerds, Samuel Smith, Tim Smits, Jeffrey Spies, Vishnu Sreekumar, Crystal Steltenpohl, Neil Stenhouse, Wojciech Świątkowski, Miguel Vadillo, Marcel Van Assen, Matt Williams, Samantha Williams, Donald Williams, Tal Yarkoni, Ignazio Ziano, and Rolf Zwaan, “Justify Your Alpha”, Nature Human Behavior, 2018. Preprint: https://osf.io/by2kc/ Paper: http://rdcu.be/HQ1y

35 - Yeganeh Doost M, Orban de Xivry J-J, Bihin B, Vandermeeren Y. Two Processes in Early Bimanual Motor Skill Learning. Front Hum Neurosci 11, 2017.

34 - Maes C, Gooijers J, Orban de Xivry JJ, Swinnen SP, Boisgontier MP, "Two hands, one brain, and aging", Neuroscience & Biobehavioral Reviews, 75, 234–256, 2017 PDF

33 - Orban de Xivry JJ, Legrain V and Lefèvre P, "Overlap of movement planning and movement execution reduces reaction time" Rapid Report in the Journal of Neurophysiology 117: 117–122, 2017. Preprint:   http://biorxiv.org/content/early/2016/06/02/039842

32 - Orban de Xivry JJ and Lefèvre P, A switching cost for motor planning, Journal of Neurophysiology, 116: 2857–2868, 2016.. Preprint: http://biorxiv.org/content/early/2016/04/12/047621

31 - Caroline Ego, Lucie Bonhomme, Jean-Jacques Orban de Xivry, David Da Fonseca, Philippe Lefèvre, Guillaume S. Masson & Christine Deruelle, "Behavioral characterization of prediction and internal models in adolescents with autistic spectrum disorders", Neuropsychologia, 91: 335–345, 2016., PDF

30 - Andrea Alamia, Jean-Jacques Orban de Xivry, Estibaliz San Anton, Etienne Olivier, Axel
Cleeremans, Alexandre Zenon, "Unconscious associative learning with conscious cues" Neuroscience of Consciousness, 2016: niw016, PDF

29 - Nozaki, Yokoi, Kimura, Hirashima, and Orban de Xivry, "Tagging motor memories with transcranial direct current stimulation allows later artificially-controlled retrieval", eLife, 2016;5:e15378 In the news (1), In the news (2)

28 - Leconte P, Orban de Xivry JJ, Stoquart G, Lejeune T, and Ronsse R, "Rhythmic arm movements are less affected than discrete ones after a stroke", Experimental Brain Research 234: 1403–1417, 2016 PDF  doi: 10.1007/s00221-015-4543-y

27 - Ego C., Yüksel D., Orban de Xivry JJ\*, Lefèvre P\* "Development of internal models and predictive abilities for visual tracking during childhood" Journal of Neurophysiology, 115: 301–309, 2016. \*co-last authors PDF doi: 10.1152/jn.00534.2015 

26- Quenon Lisa,  Orban de Xivry JJ, Hanseeuw Bernard, Ivanoiu Adrian, "Investigating associative learning effects in patients with prodromal Alzheimer’s disease using the Temporal Context Model",
Journal of the International Neuropsychological Society, 2015. doi: 10.1017/S1355617715000855. PDF

25 - Orban de Xivry Jean-Jacques and Lefèvre Philippe, "Formation of model-free motor memories during motor adaptation depends on perturbation schedule" Journal of Neurophysiology, 113: 2733–41, 2015. PDF doi: 10.1152/jn.00673.2014

24 - Ego C., Orban de Xivry JJ, Nassogne MC, Yüksel D, Lefevre P "Spontaneous improvement in oculomotor function of children with cerebral palsy", Research in Developmental Disabilities, 2015 doi: 10.1016/j.ridd.2014.10.025

23 - Orban de Xivry, Jean-Jacques and Shadmehr, Reza. Electrifying the motor engram: effects of tDCS on motor learning and control. Experimental Brain Research, 2014 DOI: 10.1007/s00221-014-4087-6

22 - Orban de Xivry, Jean-Jacques ; Coppe, Sébastien ; Blohm, Gunnar ; Lefèvre, Philippe. Kalman filtering naturally accounts for visually-guided and predictive smooth pursuit dynamics. Journal of Neuroscience, 33(44): 17301-17313 , 2013  doi: 10.1523/JNEUROSCI.2321-13.2013 PDF

21 - Orban de Xivry JJ "Trial-to-trial reoptimization of motor behavior due to changes in task demands is limited", PLoS ONE 8(6): e66013, doi: 10.1371/journal.pone.0066013 PDF

20 - Ego C., Orban de Xivry J.-J., Nassogne MC, Yüksel D, and Lefevre P. "The saccadic system does not compensate for the immaturity of the smooth pursuit system during visual tracking in children." Journal of Neurophysiology, 110(2) 358-367, 2013 ABSTRACT, PDF

19- Orban de Xivry JJ, Ahmadi-Pajouh M.A., Harran M.D., Salimpour Y., Shadmehr R. "Changes in corticospinal excitability during reach adaptation in force fields", Journal of Neurophysiology,109, 124–36, 2013 PDF

18 - Coppe S., Orban de Xivry J.-J., Yüksel D., Ivanoiu A., Lefèvre P. "Dramatic impairment of prediction due to frontal lobe degeneration", Journal of Neurophysiology, 108, 2957–2966, 2012 PDF

17 - Orban de Xivry J.-J., Mollie Marko, Sarah Pekny, Damien Pastor, Jun Izawa, Pablo Celnik, and Reza Shadmehr, "Stimulation of the human motor cortex alters generalization patterns of motor learning", Journal of Neuroscience, 31(19):7102-7110, 2011. doi: 10.1523/JNEUROSCI.0273-11.2011 PDF

16 - Galea J. M.,  Vazquez A, Pasricha N, Orban de Xivry J.-J., Celnik P "Dissociating the roles of the cerebellum and motor cortex during adaptive learning: the motor cortex retains what the cerebellum learns." Cerebral Cortex, 21(8):1761-1770, 2011. doi: 10.1093/cercor/bhq246  PDF

15 - Orban de Xivry J.-J., Criscimagna-Hemminger S. E. and Shadmehr R. "Contributions of the motor cortex to adaptive control of reaching depend on the perturbation schedule", Cerebral Cortex, 21(7):1475-1484, 2011. doi: 10.1093/cercor/bhq192 PDF

14 - Yuksel D., Orban de Xivry J.-J. and Lefèvre P. "Review of the major findings about Duane Retraction Syndrome (DRS) leading to an updated form of classification " Vision research, 50(23):2334-2347, 2010. Special issue: "Vision Research reviews Vision Research". PDF

13 - Coppe S., Orban de Xivry J.-J., Missal M. and Lefèvre P. "Biological motion influences the visuomotor transformation for smooth pursuit eye movements". Vision Research, 50: 2721-2728, 2010. Special issue: "Perception and Action". PDF

12 - Shadmehr R., Orban de Xivry J.-J., Xu-Wilson M., Shih T.Y. Temporal discounting of reward and the cost of time in motor control. Journal of Neuroscience, 30(31):10507-10516, 2010 Featured article of the week PDF Illustration

11 - Bennett S.J., Orban de Xivry J.-J., Lefevre P. and Barnes G.R., Oculomotor prediction of accelerative target motion during occlusion: long-term and short-term effects. Experimental Brain Research, 204(4):493-504, 2010. PDF

10 - Orban de Xivry J.-J., Coppe S, Lefevre P and Missal M, Biological motion drives perception and action, Journal of Vision,  10(2):6, 1-11, 2010.  PDF

9 - Orban de Xivry J.-J., Missal M and Lefevre P, Smooth pursuit performance during target blanking does not influence the trigger of predictive saccades. Journal of Vision, 9(11):7, 1-16, 2009.  PDF

8 - Orban de Xivry J.-J., Lefevre P,  Interactions between saccades and pursuit. Encyclopedia of Neuroscience (L.R. Squire, Editor), Oxford: Academic Press, 2009 ABSTRACT  PDF

7 - Orban de Xivry J.-J., Missal M and Lefevre P. A dynamic internal representation of target motion drives predictive smooth pursuit during target blanking Journal of Vision, 8(15):6, 1-13, 2008  PDF

6 - Orban de Xivry J.-J. and Ethier V Neural correlates of internal models Journal of Neuroscience 28 (32),7931-7932, 2008   PDF

5 - Yuksel D, Orban de Xivry J.-J. and Lefevre P Binocular coordination of saccades in Duane Retraction Syndrome Vision Research 48(19): 1972-1979, 2008  PDF

4 - Orban de Xivry J.-J., Ramon M, Lefevre P, Rossion B Reduced fixation on the upper area of personally familiar faces following acquired prosopagnosia Journal of Neuropsychology 2 (1): 245-268, 2008. Here, you will find some explanation about prosopagnosia.  PDF In the news

3 - Orban de Xivry J.-J. and Lefevre P. Saccades and pursuit: two outcomes of a single sensorimotor process  J Physiol. 584(1): 11-23, 2007.  PDF

2 - Bennett S.J., Orban de Xivry J.-J., Barnes G.R. and Lefevre P. Target acceleration can be extracted and represented within the predictive drive to ocular pursuit J Neurophysiol 98: 1405-1414, 2007. Selected for the editorial focus of the journal.  PDF

1 - Orban de Xivry J.-J., Bennett S.J., Lefevre P. and Barnes G.R. Evidence for synergy between saccades and smooth pursuit during transient target disappearance J Neurophysiol 95: 418-427, 2006 PDF