---
title: "team"
output:
  html_document:
    theme: spacelab
    highlight: textmate 

---


### Current lab members
* [Anouck Matthijs](https://www.kuleuven.be/wieiswie/nl/person/00147975) investigates the role of the cerebellum in age-related deficits in motor control (co-promotor is [Dante Mantini](https://www.kuleuven.be/wieiswie/nl/person/00064085))
* [Anda de Witte](https://www.kuleuven.be/wieiswie/nl/person/00146033) investigates the role of the cerebellum in age-related deficits in motor control (co-promotor is [Jolien Gooiers](https://www.kuleuven.be/wieiswie/nl/person/00065645)
* [Frea Deroost](https://www.kuleuven.be/wieiswie/nl/person/00147109) works on the effect of aging on bike ability. Co-promotor is [Friedl De Groote](https://www.kuleuven.be/wieiswie/nl/person/00046458)
* [Jef Leplae](https://www.kuleuven.be/wieiswie/nl/person/00147109) works on the effect of aging on bike ability. Co-promotor is [Friedl De Groote](https://www.kuleuven.be/wieiswie/nl/person/00046458)
* [Charlotte Heremans](https://www.kuleuven.be/wieiswie/nl/person/00153442) focuses on improving sensorimotor impairments in stroke patients withing the ROBUST project (main promotor is [Geert Verheyden](https://www.kuleuven.be/wieiswie/nl/person/00029759))
* [Ilaria Carrara](https://www.kuleuven.be/wieiswie/nl/person/00172653) investigates the effect of aging on proprioception. Her co-promotor is [An De Groef](https://www.kuleuven.be/wieiswie/nl/person/00086923)
* [Danny Koumans](https://www.kuleuven.be/wieiswie/nl/person/00172618) investigates the effect of chemotherapy on sensorimotor function. His co-promotor is [An De Groef](https://www.kuleuven.be/wieiswie/nl/person/00086923).
* [Tim Maurissens](https://www.kuleuven.be/wieiswie/nl/person/00174941) the influence of Parkinson's disease on biking abilities. His main promotor is [Moran Gilat](https://www.kuleuven.be/wieiswie/nl/person/00120552). This is an add-on to the bike project (Maestro)
* [Siqi Yang](https://www.kuleuven.be/wieiswie/nl/person/00175096) investigates the changes in brain function with sensory processing using fNIRS. Her main promotor is [Geert Verheyden](https://www.kuleuven.be/wieiswie/nl/person/00029759). This is an add-on to the Robust project.
<!-- * Ines Martins will look at the effect of sensory learning on brain activity using fMRI. Her main promotor is [Jolien Gooijers](https://www.kuleuven.be/wieiswie/nl/person/00065645).This is an add-on to the Robust project. -->
* [Stien Van De Plas](https://www.kuleuven.be/wieiswie/nl/person/00118791)  investigates the effect of aging on proprioception.

### Alumni
* [Silke Kerstens](https://www.kuleuven.be/wieiswie/nl/person/00122770) focuses on the understanding of the mechanisms of tDCS (co-promotor is [Myles Mc Laughlin](https://www.kuleuven.be/wieiswie/nl/person/00043883))
* [Britt Vandendoorent](https://www.kuleuven.be/wieiswie/nl/person/00086733) looked into the effect of tDCS on sensorimotor control in Parkinson's Disease (main promotor is [Alice Nieuwboer](https://www.kuleuven.be/wieiswie/nl/person/00014581))
* [Matheus Maia Pacheco](https://www.kuleuven.be/wieiswie/nl/person/00144244) worked on the effect of reward on motor adaptation. He also used EEG to understand the neural substrate of motor adaptation. Collaboration with [Dante Mantini](https://www.kuleuven.be/wieiswie/nl/person/00064085)
* [Mareike Gann](https://www.kuleuven.be/wieiswie/nl/person/00114278) investigated motor memory consolidation with TMS and fMRI (main promotor is [Genevieve Albouy](https://www.kuleuven.be/wieiswie/nl/person/00096297))
* [Manasa Parthasharathy](https://www.kuleuven.be/wieiswie/nl/person/00118155) worked on the use of EEG to quantify age-related deficits in sensorimotor control (main promotor is [Dante Mantini](https://www.kuleuven.be/wieiswie/nl/person/00064085))
* [Guy Rens](http://orcid.org/0000-0002-1000-529X) worked on action observation in the context of object prehension.
* [Koen Vandevoorde](https://scholar.google.be/citations?user=hezciDMAAAAJ&hl=en) was the first PhD student of the Lab. He worked on the impact of aging on motor adaptation.
* [Veerle De Rond](https://www.kuleuven.be/wieiswie/nl/person/00117680) used fNIRS to study weight shifting in young and elderly participants (main promotor is [Alice Nieuwboer](https://www.kuleuven.be/wieiswie/nl/person/00014581))
* [Leen Saenen](https://www.kuleuven.be/wieiswie/nl/person/00123401) developped new techniques to quantify sensorimotor impairments in stroke patients (main promotor is [Geert Verheyden](https://www.kuleuven.be/wieiswie/nl/person/00029759))
* [Pauline Hermans](https://www.kuleuven.be/wieiswie/nl/person/00120172) investigated the effect of aging, Parkinson's Disease and reward on motor adaptation (co-promotor is [Alice Nieuwboer](https://www.kuleuven.be/wieiswie/nl/person/00014581))